apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-green
spec:
  selector:
    matchLabels:
      app: appli-web-n
  template:
    metadata:
      labels:
        app: appli-web-n
    spec:
      containers:
        - name: appli-web-vert
        image: "us-central1-docker.pkg.dev/ornate-woodland-441008-j1/appli-web/appli-web:3.0.0"
        ports:
          - name: metrics
            containerPort: 8080