apiVersion: apps/v1
kind: appliweb-namespace
metadata:
  name: gke-web
spec:
  template:
    spec:
      containers:
        - name: appli-web-container
          image: "us-central1-docker.pkg.dev/ornate-woodland-441008-j1/appli-web/appli-web:latest"
